### ISSUE TITLE
Cache Sholiday Faboul API responses in memory

### ISSUE THREAD

**Issue by Pirayya** [Pirayya/joel-bot#2]
Since we call Sholiday every time someone uses the command `tid` we should alleviate the number of requests towards Fabouls API.

**Comment by kazie** [comment]
May be OK, but since it is HTTP, and they use a CDN. Isn't stuff already cached that way and all that is needed is to read a header the second time and see that the response has not changed and thus the OS/Web-call-framework already fixes the caching for you? :)
